# Generated by Django 3.1.3 on 2020-11-11 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssembledConstruction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('rating', models.IntegerField()),
                ('schema', models.ImageField(upload_to='')),
                ('assemble_instruction', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=25)),
                ('rating', models.IntegerField()),
                ('category', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WebServiceVisitor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebStore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='')),
                ('homepage', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WebStoreComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('component_page_link', models.URLField()),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.component')),
                ('web_store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.webstore')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionReport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('construction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assembledconstruction')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentReport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.component')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.component')),
                ('construction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assembledconstruction')),
            ],
            options={
                'unique_together': {('component_id', 'construction_id')},
            },
        ),
    ]
