# Generated by Django 3.1.3 on 2020-11-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201112_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webservicevisitor',
            name='password',
        ),
        migrations.AlterField(
            model_name='assembledconstruction',
            name='assemble_instruction',
            field=models.FileField(blank=True, upload_to='instructions/'),
        ),
        migrations.AlterField(
            model_name='assembledconstruction',
            name='image',
            field=models.ImageField(blank=True, upload_to='constructionsImages/'),
        ),
        migrations.AlterField(
            model_name='assembledconstruction',
            name='schema',
            field=models.ImageField(blank=True, upload_to='schemas/'),
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, upload_to='componentImages/'),
        ),
    ]
