# Generated by Django 3.1.3 on 2020-11-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201113_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservicevisitor',
            name='password',
            field=models.CharField(default='new_val', max_length=100),
            preserve_default=False,
        ),
    ]
