# Generated by Django 3.1.3 on 2020-11-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201113_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebServiceVisitor',
        ),
    ]
