# Generated by Django 3.1.3 on 2020-11-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_webservicevisitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebServiceVisitor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
