# Generated by Django 3.1.3 on 2020-11-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_useraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user_permissions',
        ),
    ]
