# Generated by Django 3.1.3 on 2020-11-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201113_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
