# Generated by Django 3.1.3 on 2020-11-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201113_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='assembledconstruction',
            name='name',
            field=models.CharField(default='Default name', max_length=30),
            preserve_default=False,
        ),
    ]
