# Generated by Django 3.1.3 on 2020-11-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201115_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
    ]
