# Generated by Django 3.1.3 on 2020-11-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_cart_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='construction_id',
            new_name='construction',
        ),
        migrations.RenameField(
            model_name='componentreport',
            old_name='component_id',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='constructioncomponent',
            old_name='component_id',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='constructioncomponent',
            old_name='construction_id',
            new_name='construction',
        ),
        migrations.RenameField(
            model_name='constructionreport',
            old_name='construction_id',
            new_name='construction',
        ),
        migrations.RenameField(
            model_name='webstorecomponent',
            old_name='component_id',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='webstorecomponent',
            old_name='web_store_id',
            new_name='web_store',
        ),
    ]
