# Generated by Django 3.1.3 on 2020-11-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201115_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembledconstruction',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='constructioncomponent',
            unique_together={('component_id', 'construction_id')},
        ),
    ]
