# Generated by Django 3.1.3 on 2020-11-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201122_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembledconstruction',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
