# Generated by Django 3.1.3 on 2020-11-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_assembledconstruction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembledconstruction',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
