# Generated by Django 3.1.3 on 2020-11-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20201125_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembledconstruction',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
