# Generated by Django 3.1.3 on 2020-11-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20201126_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembledconstruction',
            name='description',
        ),
    ]
