# Generated by Django 3.1.3 on 2020-11-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_assembledconstruction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembledconstruction',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
