# Generated by Django 3.1.3 on 2020-12-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_userconstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembledconstruction',
            name='instruction_images',
            field=models.FileField(blank=True, upload_to='instructions/'),
        ),
    ]
